Sync master before generating in travis
I have this error in travis now, probably because I'm using this blog from multiple machines.

```text
## Pushing generated _deploy website
To https://f4baa2a54476e1822dd5b19ae5c2d80ef66336b9@github.com/AnthonyMastrean/anthonymastrean.github.com.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://f4baa2a54476e1822dd5b19ae5c2d80ef66336b9@github.com/AnthonyMastrean/anthonymastrean.github.com.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I'm following the advice from this one blog post about syncing the master branch after setting up the gh_pages, but before generating the site.

http://blog.zerosharp.com/clone-your-octopress-to-blog-from-two-places/